server {
    listen 80;
    listen [::]:80;
    server_name liftoff.gudman.xyz;

    include /etc/nginx/snippets/acme-challenge.conf;

    location / {
        return 301 https://sealedlaunch.gudman.xyz$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name liftoff.gudman.xyz;

    ssl_certificate /etc/letsencrypt/live/liftoff.gudman.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/liftoff.gudman.xyz/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        return 301 https://sealedlaunch.gudman.xyz$request_uri;
    }
}
